# Generated by Django 5.0.3 on 2024-03-31 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetTracker', '0002_savinggoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal')], max_length=1)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('saving_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetTracker.savinggoal')),
            ],
        ),
    ]
